TicketingSystem.Web/Controllers/ProjectController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using TicketingSystem.Services;
using TicketingSystem.Web.Models.Project;

namespace TicketingSystem.Web.Controllers
{
	public class ProjectController : Controller
	{
		private readonly IProjectService _projectService;

		public ProjectController(IProjectService projectService)
		{
			_projectService = projectService;
		}

		[HttpGet]
		[Authorize]
		public IActionResult Create()
		{
			return View();
		}

		[HttpPost]
		[Authorize]
		public IActionResult Create(CreateProjectViewModel viewModel)
		{
			HttpContextAccessor accessor = new HttpContextAccessor();

			var claims = accessor.HttpContext.User.Claims;
			int userId = -1;

			foreach (var claim in claims)
			{
				string claimValue = claim.Value;
				int.TryParse(claimValue, out userId);
			}

			var model = new CreateProjectModel(viewModel.Name, viewModel.Description, userId);

			try
			{
				_projectService.Create(model);
			}
			catch (Exception e)
			{
				viewModel.ErrorMessage = e.Message;
				return View(nameof(Create), viewModel);
			}

			return RedirectToAction(nameof(HomeController.Index), "Home");
		}
	}
}

TicketingSystem.Web/Controllers/TicketController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using TicketingSystem.Services;
using TicketingSystem.Services.Impl;
using TicketingSystem.Web.Models.Message;
using TicketingSystem.Web.Models.Ticket;

namespace TicketingSystem.Web.Controllers
{
	public class TicketController : Controller
	{
		public readonly ITicketService _ticketService = new TicketService();

		public readonly IProjectService _projectService = new ProjectService();

		public readonly IUserService _userService = new UserService();

		public readonly IMessageService _messageService = new MessageService();

		private const int PageSize = 5;

		public TicketController(ITicketService ticketService, IProjectService projectService,
			IUserService userService, IMessageService messageService)
		{
			_ticketService = ticketService;
			_projectService = projectService;
			_userService = userService;
			_messageService = messageService;
		}

		[HttpGet]
		[Authorize]
		public IActionResult Create()
		{
			TicketFormViewModel model = new TicketFormViewModel();

			GetProjectsName(model);

			return View(model);
		}

		[HttpPost]
		[Authorize]
		public IActionResult Create(TicketFormViewModel viewModel)
		{
			var model = new CreateTicketModel();

			viewModel.ProjectId = _projectService.GetByName(viewModel.ProjectName).Id;
			int userId = GetUserId();

			string path = viewModel.FilePath;
			if (!string.IsNullOrEmpty(path))
			{
				byte[] file = System.IO.File.ReadAllBytes(path);
				string fileName = Path.GetFileName(path);

				model = new CreateTicketModel
				{
					ProjectId = viewModel.ProjectId,
					TicketTitle = viewModel.TicketTitle,
					TicketDescription = viewModel.Description,
					TicketState = viewModel.TicketState.Replace(" ", ""),
					TicketType = viewModel.TicketType.Replace(" ", ""),
					FileContent = file,
					FileName = fileName,
					SubmitterId = userId
				};
			}

			model = new CreateTicketModel
			{
				ProjectId = viewModel.ProjectId,
				TicketTitle = viewModel.TicketTitle,
				TicketDescription = viewModel.Description,
				TicketState = viewModel.TicketState.Replace(" ", ""),
				TicketType = viewModel.TicketType.Replace(" ", ""),
				SubmitterId = userId
			};

			try
			{
				_ticketService.Create(model);
			}
			catch (System.Exception e)
			{
				viewModel.ErrorMessage = e.Message;
				GetProjectsName(viewModel);
				return View(nameof(Create), viewModel);
			}

			return RedirectToAction(nameof(HomeController.Index), "Home");
		}

		[HttpGet]
		[Authorize]
		public IActionResult ListTickets(int page = 1)
		{
			int userId = GetUserId();
			var ticketsToShow = new List<OverviewTicketViewModel>();
			if (User.IsInRole("Client"))
			{
				int ticketsCount = _ticketService.GetAllTicketsForClient(userId).Count();

				var tickets = _ticketService.GetAllTicketsToShowForClient(userId, page, PageSize);

				CreateOverviewTickets(ticketsToShow, tickets);

				return View(new TicketListingViewModel
				{
					Tickets = ticketsToShow,
					CurrentPage = page,
					TotalPages = (int)Math.Ceiling(ticketsCount / (double)PageSize)
				});
			}
			else
			{
				int ticketsCount = _ticketService.GetAllTicketsForAdminAndSupport().Count();

				var tickets = _ticketService.GetAllTicketsToShowForAdminAndSupport();

				CreateOverviewTickets(ticketsToShow, _ticketService.GetAllTicketsToShowForAdminAndSupport(page, PageSize));

				return View(new TicketListingViewModel
				{
					Tickets = ticketsToShow,
					CurrentPage = page,
					TotalPages = (int)Math.Ceiling(ticketsCount / (double)PageSize)
				});

			}
		}

		[HttpPost]
		[Authorize]
		public IActionResult DeleteTicket(int id)
		{
			_ticketService.Delete(id);

			return RedirectToAction(nameof(ListTickets));
		}

		[HttpGet]
		[Authorize]
		public IActionResult View(int id)
		{
			Ticket ticket = _ticketService.GetByTicketId(id);

			int currnetUserId = _userService.GetByUsername(User.Identity.Name).Id;

			if (User.IsInRole("Client") && currnetUserId != ticket.SubmitterId)
			{
				return NotFound();
			}

			var model = new ViewTicketViewModel();

			try
			{
				var messages = new List<Message>();

				messages.AddRange(_messageService.Get(id));

				var viewMessages = new List<MessageViewModel>();

				foreach (var message in messages)
				{

					var viewModel = new MessageViewModel
					{
						Id = message.Id,
						Content = message.Content,
						PublishingDate = message.PublishingDate,
						State = message.State,
						UserId = message.UserId,
						Username = message.Username
					};

					viewMessages.Add(viewModel);
				}

				model = new ViewTicketViewModel
				{
					TicketId = id,
					TicketTitle = ticket.Title,
					Description = ticket.Description,
					FileName = ticket.FileName,
					ProjectName = _projectService.GetById(ticket.ProjectId).Name,
					SubmitterId = ticket.SubmitterId,
					TicketState = ticket.State,
					TicketType = ticket.Type,
					Messages = viewMessages
				};

				return View(model);
			}
			catch
			{
				model = new ViewTicketViewModel
				{
					TicketId = id,
					TicketTitle = ticket.Title,
					Description = ticket.Description,
					FileName = ticket.FileName,
					ProjectName = _projectService.GetById(ticket.ProjectId).Name,
					SubmitterId = ticket.SubmitterId,
					TicketState = ticket.State,
					TicketType = ticket.Type
				};
				return View(model);
			}


		}

		[HttpGet]
		[Authorize]
		public IActionResult Edit(int id)
		{
			Ticket ticket = _ticketService.GetByTicketId(id);

			int currnetUserId = _userService.GetByUsername(User.Identity.Name).Id;

			if (User.IsInRole("Client") && currnetUserId != ticket.SubmitterId)
			{
				return NotFound();
			}

			var model = new TicketFormViewModel
			{
				TicketId = id,
				TicketTitle = ticket.Title,
				Description = ticket.Description,
				FileName = ticket.FileName,
				ProjectName = _projectService.GetById(ticket.ProjectId).Name,
				SubmitterId = ticket.SubmitterId,
				TicketState = ticket.State,
				TicketType = ticket.Type,
			};

			return View(model);
		}

		[HttpGet]
		[Authorize]
		public IActionResult Delete(int id)
		{
			Ticket ticket = _ticketService.GetByTicketId(id);

			int currnetUserId = _userService.GetByUsername(User.Identity.Name).Id;

			if (User.IsInRole("Client") && currnetUserId != ticket.SubmitterId)
			{
				return NotFound();
			}

			var model = new TicketFormViewModel
			{
				TicketId = id,
				TicketTitle = ticket.Title,
				Description = ticket.Description,
				FileName = ticket.FileName,
				ProjectName = _projectService.GetById(ticket.ProjectId).Name,
				SubmitterId = ticket.SubmitterId,
				TicketState = ticket.State,
				TicketType = ticket.Type,
			};

			return View(model);
		}

		[HttpPost]
		[Authorize]
		public IActionResult Delete(int id, TicketFormViewModel viewTicket)
		{
			_ticketService.Delete(id);

			return RedirectToAction(nameof(ListTickets));
		}

		[HttpPost]
		[Authorize]
		public IActionResult Edit(int id, TicketFormViewModel viewModel)
		{
			int currnetUserId = _userService.GetByUsername(User.Identity.Name).Id;

			if (User.IsInRole("Client") && currnetUserId != viewModel.SubmitterId)
			{
				return NotFound();
			}

			var model = new UpdateTicketModel
			{
				Id = id,
				ProjectName = viewModel.ProjectName,
				Title = viewModel.TicketTitle,
				Description = viewModel.Description,
				State = viewModel.TicketState.Replace(" ", ""),
				Type = viewModel.TicketType.Replace(" ", ""),
			};

			try
			{
				_ticketService.Edit(model);
			}
			catch (Exception e)
			{
				viewModel.ErrorMessage = e.Message;
				viewModel.ProjectName = _projectService.GetById(_ticketService.GetByTicketId(id).ProjectId).Name;
				return View(viewModel);
			}

			return RedirectToAction(nameof(ListTickets));
		}

		private void CreateOverviewTickets(List<OverviewTicketViewModel> overviewTickets, IEnumerable<Ticket> tickets)
		{
			foreach (var ticket in tickets)
			{
				var viewModel = new OverviewTicketViewModel
				{
					Id = ticket.Id,
					Title = ticket.Title,
					ProjectName = _projectService.GetById(ticket.ProjectId).Name,
					SubmissionDate = ticket.SubmissionDate,
					SumitterName = _userService.GetByUserId(ticket.SubmitterId).Username,
					TicketState = ticket.State
				};
				overviewTickets.Add(viewModel);
			}
		}

		private static int GetUserId()
		{
			HttpContextAccessor accessor = new HttpContextAccessor();
			var claims = accessor.HttpContext.User.Claims;
			int userId = -1;

			foreach (var claim in claims)
			{
				string claimValue = claim.Value;
				int.TryParse(claimValue, out userId);
			}

			return userId;
		}

		private void GetProjectsName(TicketFormViewModel viewModel)
		{
			List<string> projectNames = _projectService.Get().Select(pr => pr.Name).ToList();

			viewModel.ProjectNames = new List<string>();

			foreach (var name in projectNames)
			{
				viewModel.ProjectNames.Add(name);
			}
		}
	}
}

TicketingSystem.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport"
		  content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - Ticketing System</title>

	<environment include="Development">
		<link rel="stylesheet"
			  href="~/lib/bootstrap/dist/css/bootstrap.css" />
		<link rel="stylesheet"
			  href="~/css/site.css" />
		<link rel="stylesheet"
			  href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css" />
		<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css"
			  rel="stylesheet"
			  id="bootstrap-css" />

	</environment>
	<environment exclude="Development">
		<link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
			  asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
			  asp-fallback-test-class="sr-only"
			  asp-fallback-test-property="position"
			  asp-fallback-test-value="absolute" />
		<link rel="stylesheet"
			  href="~/css/site.min.css"
			  asp-append-version="true" />
	</environment>
</head>

<body>
	<nav class="navbar navbar-inverse navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
					<span class="sr-only">
						Toggle navigation
					</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a asp-area=""
				   asp-controller="Home"
				   asp-action="Index"
				   class="navbar-brand">
					Ticketing System
				</a>
			</div>
			<div class="navbar-collapse collapse">
				<ul class="nav navbar-nav">
					<li>
						<a asp-area=""
						   asp-controller="Ticket"
						   asp-action="ListTickets">
							List Tickets
						</a>
					</li>
					@if (User.Identity.IsAuthenticated)
					{
						<li>
							<a asp-area=""
							   asp-controller="Ticket"
							   asp-action="Create">
								Create Ticket
							</a>
						</li>
					}
					@if (User.IsInRole("Administrator"))
					{
						<li class="dropdown">
							<a class="dropdown-toggle" data-toggle="dropdown">
								Admin Actions
								<span class="caret"></span>
							</a>
							<ul class="dropdown-menu">
								<li>
									<a asp-area=""
									   asp-controller="Project"
									   asp-action="Create">
										Create Project
									</a>
								</li>
								<li>
									<a asp-area=""
									   asp-controller="Account"
									   asp-action="UsersToProcess">
										Approve Users
									</a>
								</li>
								<li>
									<a asp-area=""
									   asp-controller="Account"
									   asp-action="Register">
										Register User
									</a>
								</li>
								<li>
									<a asp-area=""
									   asp-controller="Account"
									   asp-action="BrowseUsers">
										Browse Users
									</a>
								</li>
							</ul>
						</li>
					}
				</ul>
				@await Html.PartialAsync("_LoginPartial")
			</div>
		</div>
	</nav>
	<div class="container body-content">
		@RenderBody()
		<hr />
		<footer>
			<p>&copy; 2018 - Ticketing System</p>
		</footer>
	</div>
	<environment include="Development">
		<script src="~/lib/jquery/dist/jquery.js"></script>
		<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
		<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
		<script src="~/js/site.js" asp-append-version="true"></script>
	</environment>
	<environment exclude="Development">
		<script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
				asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
				asp-fallback-test="window.jQuery"
				crossorigin="anonymous"
				integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
		</script>
		<script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
				asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
				asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
				crossorigin="anonymous"
				integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
		</script>
		<script src="~/js/site.min.js" asp-append-version="true"></script>
	</environment>

	@RenderSection("Scripts", required: false)
</body>
</html>